language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - bin/phpspec run -fprogress
  - bin/behat -fprogress
  - bin/php-cs-fixer fix --dry-run --verbose

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true